# Generated by Django 4.2.1 on 2023-06-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="Date",
            field=models.DateField(auto_created=True),
        ),
    ]
