# Generated by Django 4.2.1 on 2023-06-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0004_alter_todo_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="Date",
            field=models.DateField(),
        ),
    ]
